<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'reference' => 'ORD-0001',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '7.00000000',
                'tax_charge' => '31.11900000',
                'shipping_title' => 'Flat Rate',
                'total' => '923.11900000',
                'paid' => '923.12000000',
                'total_quantity' => '3.00000000',
                'amount_received' => '923.12000000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'reference' => 'ORD-0002',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '0.00000000',
                'tax_charge' => '2.02400000',
                'shipping_title' => 'Local Pickup',
                'total' => '42.02400000',
                'paid' => '42.02000000',
                'total_quantity' => '1.00000000',
                'amount_received' => '42.02000000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 2,
                'reference' => 'ORD-0003',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '2.00000000',
                'tax_charge' => '1.26500000',
                'shipping_title' => 'Flat Rate',
                'total' => '28.26500000',
                'paid' => '0.28265000',
                'total_quantity' => '1.00000000',
                'amount_received' => '0.28265000',
                'order_status_id' => 3,
                'is_delivery' => 0,
                'payment_status' => 'Paid',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 2,
                'reference' => 'ORD-0004',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '2.00000000',
                'tax_charge' => '3.79500000',
                'shipping_title' => 'Flat Rate',
                'total' => '80.79500000',
                'paid' => '0.00000000',
                'total_quantity' => '1.00000000',
                'amount_received' => '0.00000000',
                'order_status_id' => 1,
                'is_delivery' => 0,
                'payment_status' => 'Unpaid',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 2,
                'reference' => 'ORD-0005',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '0.00000000',
                'tax_charge' => '1.26500000',
                'shipping_title' => 'Local Pickup',
                'total' => '26.26500000',
                'paid' => '0.00000000',
                'total_quantity' => '1.00000000',
                'amount_received' => '0.00000000',
                'order_status_id' => 5,
                'is_delivery' => 0,
                'payment_status' => 'Unpaid',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 2,
                'reference' => 'ORD-0006',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '3.00000000',
                'tax_charge' => '18.72200000',
                'shipping_title' => 'Flat Rate',
                'total' => '391.72200000',
                'paid' => '3.91722000',
                'total_quantity' => '1.00000000',
                'amount_received' => '3.91722000',
                'order_status_id' => 3,
                'is_delivery' => 0,
                'payment_status' => 'Paid',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 4,
                'reference' => 'ORD-0007',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '30.00000000',
                'tax_charge' => '8.16000000',
                'shipping_title' => 'Flat Rate',
                'total' => '446.16000000',
                'paid' => '446.16000000',
                'total_quantity' => '3.00000000',
                'amount_received' => '446.16000000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 5,
                'reference' => 'ORD-0008',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '1.00000000',
                'tax_charge' => '0.56000000',
                'shipping_title' => 'Local Pickup',
                'total' => '79.56000000',
                'paid' => '0.00000000',
                'total_quantity' => '2.00000000',
                'amount_received' => '0.00000000',
                'order_status_id' => 6,
                'is_delivery' => 0,
                'payment_status' => 'Unpaid',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 6,
                'reference' => 'ORD-0009',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '1.00000000',
                'tax_charge' => '3.96000000',
                'shipping_title' => 'Local Pickup',
                'total' => '202.96000000',
                'paid' => '202.96000000',
                'total_quantity' => '4.00000000',
                'amount_received' => '202.96000000',
                'order_status_id' => 3,
                'is_delivery' => 0,
                'payment_status' => 'Paid',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 20,
                'reference' => 'ORD-0010',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '1.00000000',
                'tax_charge' => '0.40480000',
                'shipping_title' => 'Local Pickup',
                'total' => '309.40480000',
                'paid' => '309.40000000',
                'total_quantity' => '3.00000000',
                'amount_received' => '309.40000000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 6,
                'reference' => 'ORD-0011',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '1.00000000',
                'tax_charge' => '8.58000000',
                'shipping_title' => 'Local Pickup',
                'total' => '448.58000000',
                'paid' => '4.48580000',
                'total_quantity' => '7.00000000',
                'amount_received' => '4.48580000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 7,
                'reference' => 'ORD-0012',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '15.00000000',
                'tax_charge' => '5.56000000',
                'shipping_title' => 'Flat Rate',
                'total' => '298.56000000',
                'paid' => '298.56000000',
                'total_quantity' => '5.00000000',
                'amount_received' => '298.56000000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 9,
                'reference' => 'ORD-0013',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => NULL,
                'tax_charge' => '0.00000000',
                'shipping_title' => NULL,
                'total' => '50.00000000',
                'paid' => '50.00000000',
                'total_quantity' => '1.00000000',
                'amount_received' => '50.00000000',
                'order_status_id' => 4,
                'is_delivery' => 1,
                'payment_status' => 'Paid',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 8,
                'reference' => 'ORD-0014',
                'note' => NULL,
                'order_date' => randomDateBefore(90),
                'currency_id' => 3,
                'leave_door' => NULL,
                'other_discount_amount' => '0.00000000',
                'other_discount_type' => NULL,
                'shipping_charge' => '15.00000000',
                'tax_charge' => '24.18000000',
                'shipping_title' => 'Flat Rate',
                'total' => '1248.18000000',
                'paid' => '12.48180000',
                'total_quantity' => '3.00000000',
                'amount_received' => '12.48180000',
                'order_status_id' => 3,
                'is_delivery' => 0,
                'payment_status' => 'Paid',
            ),
        ));
        
        
    }
}