@extends('errors::minimal-layout')
@section('title', '419 Authentication Timeout')
@section('code', '419')
@section('name', 'Authentication Timeout')
@section('message', __('Authentication Timeout'))
