@extends('errors::minimal-layout')
@section('title', '429 Too Many Requests')
@section('code', '429')
@section('name', 'Too Many Requests')
@section('message', __('Too many requests has given, try again later.'))
