@extends('errors::minimal-layout')
@section('title', '503 Service Unavailable')
@section('code', '503')
@section('name', 'Service Unavailable')
@section('message', __('The server is currently unavailable'))
