<?php

namespace Modules\CMS\Database\Seeders;

use Illuminate\Database\Seeder;

class SlidesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        $data = array (
            0 =>
            array (
                'id' => 1,
                'slider_id' => 1,
                'title_text' => NULL,
                'title_animation' => 'fadeIn',
                'title_delay' => 0.02,
                'title_font_color' => '#737373',
                'title_font_size' => NULL,
                'title_direction' => 'left',
                'sub_title_text' => NULL,
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.02,
                'sub_title_font_color' => '#000000',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => NULL,
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.03,
                'description_title_font_color' => '#000000',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Fashion',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            1 =>
            array (
                'id' => 2,
                'slider_id' => 1,
                'title_text' => 'Hena’s Lifestyle',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.02,
                'title_font_color' => '#dcdbdb',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'MODERN FURNITURES',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.02,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Flash Sale up to <br><span style="color:#E43147;margin-top:10px">10% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.02,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Home%20Appliances',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            2 =>
            array (
                'id' => 3,
                'slider_id' => 1,
                'title_text' => 'Custom Men’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.02,
                'title_font_color' => '#878787',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'SPORTS GEAR',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.02,
                'sub_title_font_color' => '#000000',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Flash Sale up to <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.02,
                'description_title_font_color' => '#000000',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Automotive%20%26%20Motorbike',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            3 =>
            array (
                'id' => 4,
                'slider_id' => 1,
                'title_text' => 'CellHive Gadgets',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.02,
                'title_font_color' => '#8c8c8c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'GEN V EARPHONES',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.02,
                'sub_title_font_color' => '#000000',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Sale up to <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.02,
                'description_title_font_color' => '#000000',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Electronic%20Accessories',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            4 =>
            array (
                'id' => 5,
                'slider_id' => 2,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#069c6f',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'GROCERY STORE',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home Delivery<br><span style="color:#FA886A;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Food%20Preparation',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            5 =>
            array (
                'id' => 6,
                'slider_id' => 2,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#069c6f',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'ALL VEGGIES',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#FA886A;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Food%20Preparation',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            6 =>
            array (
                'id' => 7,
                'slider_id' => 2,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#2c2c2c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'TROPICANOS',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#069c6f',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery<br><span style="color:#2c2c2c;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Food%20Preparation',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#069c6f',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            7 =>
            array (
                'id' => 8,
                'slider_id' => 2,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#069c6f',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'PURE HONEY',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#FA886A;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Food%20Preparation',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            8 =>
            array (
                'id' => 9,
                'slider_id' => 3,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#2c2c2c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Panjabi%20%26%20Fatua',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            9 =>
            array (
                'id' => 10,
                'slider_id' => 3,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#2c2c2c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Panjabi%20%26%20Fatua',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            10 =>
            array (
                'id' => 11,
                'slider_id' => 3,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#ffffff',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'ALL ABOUT MEN',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery 30% OFF',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Jackets%20%26%20Coats',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            11 =>
            array (
                'id' => 12,
                'slider_id' => 3,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => 0.2,
                'title_font_color' => '#2c2c2c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'AGE DOESN’T MATTER',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 26,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Jackets%20%26%20Coats',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            12 =>
            array (
                'id' => 13,
                'slider_id' => 4,
                'title_text' => 'Martvill’s Luxury',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#fcca19',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'KING ROE’S SUIT',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => 0.2,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Jackets%20%26%20Coats',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            13 =>
            array (
                'id' => 15,
                'slider_id' => 4,
                'title_text' => 'Watches',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ffffff',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'SUPREME ELEGANCE',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Men%27s%20Watch',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            14 =>
            array (
                'id' => 16,
                'slider_id' => 4,
                'title_text' => 'Suits & Trousers',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#2c2c2c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'WILD ATTITUDES',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Jackets%20%26%20Coats',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            15 =>
            array (
                'id' => 17,
                'slider_id' => 5,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#2c2c2c',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Jackets%20%26%20Coats',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            16 =>
            array (
                'id' => 18,
                'slider_id' => 5,
                'title_text' => 'Sports Zone',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#e43147',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'FIGHT & BE FREE',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Boxing%2C%20Martial%20Arts%20%26%20MMA',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#e43147',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            17 =>
            array (
                'id' => 19,
                'slider_id' => 5,
                'title_text' => 'Martvill’s Footwear',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#fcca19',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'STYLE UP YOUR FEET',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Shoes',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            18 =>
            array (
                'id' => 20,
                'slider_id' => 5,
                'title_text' => 'Home Sweet Home',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#898989',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'DECORATE YOUR HOMES',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Small%20Kitchen%20Appliances',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            19 =>
            array (
                'id' => 21,
                'slider_id' => 6,
                'title_text' => 'Groom you kiddos',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ffffff',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'LITTLE STARS SHOP',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Up to 30% OFF',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/earch-products?categories=Babies%20%26%20Toys',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            20 =>
            array (
                'id' => 22,
                'slider_id' => 6,
                'title_text' => 'Computers',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#898989',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'BUSINESS LAPTOPS',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Up to 30% OFF',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#e43147',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Laptops',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            21 =>
            array (
                'id' => 23,
                'slider_id' => 6,
                'title_text' => 'Mac & iPhones',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#898989',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'TRUE CLASS',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Delivery',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#e43147',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Smartphones',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            22 =>
            array (
                'id' => 24,
                'slider_id' => 6,
                'title_text' => 'Mobile Phones',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ffffff',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'MOST WANTED',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Starting From $199',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/search-products?categories=Smartphones',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#fcca19',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            23 =>
            array (
                'id' => 25,
                'slider_id' => 7,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ff6b00',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#000000',
                'description_title_font_size' => NULL,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#ff324d',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            24 =>
            array (
                'id' => 26,
                'slider_id' => 7,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ff6b00',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'STYLE YOUR CHILD',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#ff324d',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            25 =>
            array (
                'id' => 27,
                'slider_id' => 7,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#898989',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'JAPANESE SAMURAI SUIT',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#ff324d',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            26 =>
            array (
                'id' => 28,
                'slider_id' => 8,
                'title_text' => '<p style="margin-top: 64px;">New Martvill’s</p>',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#23c692',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'CLOTHES YOU WILL LOVE',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#ff324d',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            27 =>
            array (
                'id' => 29,
                'slider_id' => 7,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#778777',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'CORPORATE ZONE',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br><span style="color:#E43147;margin-top:10px">30% OFF<span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#ff324d',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            28 =>
            array (
                'id' => 30,
                'slider_id' => 9,
                'title_text' => NULL,
                'title_animation' => 'slideInDown',
                'title_delay' => 0.0,
                'title_font_color' => '#292929',
                'title_font_size' => 16,
                'title_direction' => 'left',
                'sub_title_text' => '<p style="margin-bottom: 30px;">A Revolution</p>',
                'sub_title_animation' => 'slideInDown',
                'sub_title_delay' => 0.3,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 80,
                'sub_title_direction' => 'left',
                'description_title_text' => 'In Retail',
                'description_title_animation' => 'slideInDown',
                'description_title_delay' => 0.3,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 80,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'slideInDown',
                'button_delay' => 0.6,
                'is_open_in_new_window' => 'Yes',
            ),
            29 =>
            array (
                'id' => 31,
                'slider_id' => 9,
                'title_text' => NULL,
                'title_animation' => 'slideInDown',
                'title_delay' => 0.0,
                'title_font_color' => '#292929',
                'title_font_size' => 16,
                'title_direction' => 'left',
                'sub_title_text' => '<p style="margin-bottom: 30px;">Summer Hot</p>',
                'sub_title_animation' => 'slideInDown',
                'sub_title_delay' => 0.3,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 80,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Key Trends',
                'description_title_animation' => 'slideInDown',
                'description_title_delay' => 0.3,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 60,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'slideInDown',
                'button_delay' => 0.6,
                'is_open_in_new_window' => 'Yes',
            ),
            30 =>
            array (
                'id' => 32,
                'slider_id' => 9,
                'title_text' => NULL,
                'title_animation' => 'slideInDown',
                'title_delay' => 0.0,
                'title_font_color' => '#292929',
                'title_font_size' => 16,
                'title_direction' => 'left',
                'sub_title_text' => '<p style="margin-bottom: 30px;">Baby Doll</p>',
                'sub_title_animation' => 'slideInDown',
                'sub_title_delay' => 0.3,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 80,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Collar Blouse',
                'description_title_animation' => 'slideInDown',
                'description_title_delay' => 0.3,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 60,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'slideInDown',
                'button_delay' => 0.6,
                'is_open_in_new_window' => 'Yes',
            ),
            31 =>
            array (
                'id' => 33,
                'slider_id' => 10,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#292929',
                'title_font_size' => 26,
                'title_direction' => 'right',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'right',
                'description_title_text' => 'Sale up to 30% OFF',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 26,
                'description_title_direction' => 'right',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'right',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            32 =>
            array (
                'id' => 34,
                'slider_id' => 11,
                'title_text' => 'SUMMER COLLECTION',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#000000',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'A Revolution',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 50,
                'sub_title_direction' => 'left',
                'description_title_text' => 'In Retail',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 40,
                'description_title_direction' => 'left',
                'button_title' => 'Explore Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            33 =>
            array (
                'id' => 35,
                'slider_id' => 12,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#292929',
                'title_font_size' => 26,
                'title_direction' => 'center',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'center',
                'description_title_text' => 'Sale up to 30% OFF',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 26,
                'description_title_direction' => 'center',
                'button_title' => 'Visit Shop',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'center',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            34 =>
            array (
                'id' => 36,
                'slider_id' => 13,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#292929',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'LIVING & FASHION',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Sale up to 30% OFF',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Explore Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            35 =>
            array (
                'id' => 37,
                'slider_id' => 13,
                'title_text' => 'SUMMER COLLECTION',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#292929',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'A Revolution',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#292929',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'In Retail',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#292929',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Explore Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => 0.0,
                'is_open_in_new_window' => 'Yes',
            ),
            36 =>
            array (
                'id' => 38,
                'slider_id' => 14,
                'title_text' => 'Martvill Furnitures',
                'title_animation' => 'slideInDown',
                'title_delay' => 0.0,
                'title_font_color' => '#ff5b30',
                'title_font_size' => 24,
                'title_direction' => 'left',
                'sub_title_text' => 'NO MORE',
                'sub_title_animation' => 'slideInDown',
                'sub_title_delay' => 0.4,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 56,
                'sub_title_direction' => 'left',
                'description_title_text' => 'BORING HOMES',
                'description_title_animation' => 'slideInDown',
                'description_title_delay' => 0.8,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 56,
                'description_title_direction' => 'left',
                'button_title' => 'Explore All',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#ffb648',
                'button_position' => 'left',
                'button_animation' => 'slideInDown',
                'button_delay' => 1.2,
                'is_open_in_new_window' => 'Yes',
            ),
            37 =>
            array (
                'id' => 39,
                'slider_id' => 14,
                'title_text' => 'Martvill Furnitures',
                'title_animation' => 'slideInDown',
                'title_delay' => 0.0,
                'title_font_color' => '#ff5b30',
                'title_font_size' => 24,
                'title_direction' => 'left',
                'sub_title_text' => 'EXOTIC AND',
                'sub_title_animation' => 'slideInDown',
                'sub_title_delay' => 0.4,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 56,
                'sub_title_direction' => 'left',
                'description_title_text' => 'MINIMAL',
                'description_title_animation' => 'slideInDown',
                'description_title_delay' => 0.8,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 56,
                'description_title_direction' => 'left',
                'button_title' => 'Explore All',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#ffb648',
                'button_position' => 'left',
                'button_animation' => 'slideInDown',
                'button_delay' => 1.2,
                'is_open_in_new_window' => 'Yes',
            ),
            38 =>
            array (
                'id' => 40,
                'slider_id' => 14,
                'title_text' => 'New Martvill’s',
                'title_animation' => 'slideInDown',
                'title_delay' => 0.0,
                'title_font_color' => '#ff5b30',
                'title_font_size' => 24,
                'title_direction' => 'left',
                'sub_title_text' => 'CLASSIC YET',
                'sub_title_animation' => 'slideInDown',
                'sub_title_delay' => 0.4,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 56,
                'sub_title_direction' => 'left',
                'description_title_text' => 'MODERN',
                'description_title_animation' => 'slideInDown',
                'description_title_delay' => 0.8,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 56,
                'description_title_direction' => 'left',
                'button_title' => 'Explore All',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#ffb648',
                'button_position' => 'left',
                'button_animation' => 'slideInDown',
                'button_delay' => 1.2,
                'is_open_in_new_window' => 'Yes',
            ),
            39 =>
            array (
                'id' => 41,
                'slider_id' => 15,
                'title_text' => 'Martvill Furniture',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#898989',
                'title_font_size' => 22,
                'title_direction' => 'left',
                'sub_title_text' => 'MINIMAL IN EVERYWAY',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 34,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Free Home delivery <br> <span style="color: #FF693A">30% OFF</span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 20,
                'description_title_direction' => 'left',
                'button_title' => 'Shop Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#ffb648',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => NULL,
                'is_open_in_new_window' => 'Yes',
            ),
            40 =>
            array (
                'id' => 42,
                'slider_id' => 16,
                'title_text' => 'Martvill Furniture',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#898989',
                'title_font_size' => 26,
                'title_direction' => 'center',
                'sub_title_text' => 'MINIMALISTIC IS EVERYWAY',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#2c2c2c',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'center',
                'description_title_text' => 'Get the best with worldwide shipping <br> <span style="color: #FF693A">up to 30% Discount</span>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#2c2c2c',
                'description_title_font_size' => 26,
                'description_title_direction' => 'center',
                'button_title' => NULL,
                'button_link' => NULL,
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#000000',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => NULL,
                'is_open_in_new_window' => 'Yes',
            ),
            41 =>
            array (
                'id' => 43,
                'slider_id' => 17,
                'title_text' => 'NEW COLLECTION',
                'title_animation' => 'slideInLeft',
                'title_delay' => 0.0,
                'title_font_color' => '#333333',
                'title_font_size' => 13,
                'title_direction' => 'left',
                'sub_title_text' => 'Find Your New <br> Favorite Clothing',
                'sub_title_animation' => 'slideInLeft',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#333333',
                'sub_title_font_size' => 45,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Keep perfect time with the contemporary, expertly-crafted designs.',
                'description_title_animation' => 'slideInLeft',
                'description_title_delay' => 0.4,
                'description_title_font_color' => '#777777',
                'description_title_font_size' => 13,
                'description_title_direction' => 'left',
                'button_title' => 'DISCOVER NOW',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#48cab2',
                'button_position' => 'left',
                'button_animation' => 'slideInLeft',
                'button_delay' => 0.6,
                'is_open_in_new_window' => 'Yes',
            ),
            42 =>
            array (
                'id' => 44,
                'slider_id' => 17,
                'title_text' => 'NEED-IT-NOW',
                'title_animation' => 'slideInUp',
                'title_delay' => 0.0,
                'title_font_color' => '#333333',
                'title_font_size' => 13,
                'title_direction' => 'right',
                'sub_title_text' => 'Must-Haves <br> for the Season',
                'sub_title_animation' => 'slideInUp',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#333333',
                'sub_title_font_size' => 45,
                'sub_title_direction' => 'right',
                'description_title_text' => 'Contemporary, minimal and beautifully iconic.',
                'description_title_animation' => 'slideInUp',
                'description_title_delay' => 0.4,
                'description_title_font_color' => '#777777',
                'description_title_font_size' => 13,
                'description_title_direction' => 'right',
                'button_title' => 'SHOP NOW',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#48cab2',
                'button_position' => 'right',
                'button_animation' => 'slideInUp',
                'button_delay' => 0.6,
                'is_open_in_new_window' => 'Yes',
            ),
            43 =>
            array (
                'id' => 45,
                'slider_id' => 17,
                'title_text' => 'DON\'T MISS TODAY\'S FEATURED DEALS',
                'title_animation' => 'slideInRight',
                'title_delay' => 0.0,
                'title_font_color' => '#000000',
                'title_font_size' => 13,
                'title_direction' => 'left',
                'sub_title_text' => 'Get up to <br> 50% Off',
                'sub_title_animation' => 'slideInRight',
                'sub_title_delay' => 0.2,
                'sub_title_font_color' => '#333333',
                'sub_title_font_size' => 45,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Here to bring your life style to the next level.',
                'description_title_animation' => 'slideInRight',
                'description_title_delay' => 0.4,
                'description_title_font_color' => '#000000',
                'description_title_font_size' => 13,
                'description_title_direction' => 'left',
                'button_title' => 'Explore All',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#ffffff',
                'button_bg_color' => '#48cab2',
                'button_position' => 'left',
                'button_animation' => 'slideInRight',
                'button_delay' => 0.6,
                'is_open_in_new_window' => 'Yes',
            ),
            44 =>
            array (
                'id' => 46,
                'slider_id' => 18,
                'title_text' => 'Martvill Digital',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ffffff',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'PREMIUM TUTORIALS <br> & SOFTWARES',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 40,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Right at your fingertips',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Get Started',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#ffffff',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => NULL,
                'is_open_in_new_window' => 'Yes',
            ),
            45 =>
            array (
                'id' => 47,
                'slider_id' => 19,
                'title_text' => 'Martvill courses will take you',
                'title_animation' => 'fadeIn',
                'title_delay' => NULL,
                'title_font_color' => '#ffffff',
                'title_font_size' => 26,
                'title_direction' => 'left',
                'sub_title_text' => 'OUT OF THIS WORLD',
                'sub_title_animation' => 'fadeIn',
                'sub_title_delay' => NULL,
                'sub_title_font_color' => '#ffffff',
                'sub_title_font_size' => 48,
                'sub_title_direction' => 'left',
                'description_title_text' => 'Web Development course  <p style="color: #FFCF23">ON SALE UPTO 60%</p>',
                'description_title_animation' => 'fadeIn',
                'description_title_delay' => NULL,
                'description_title_font_color' => '#ffffff',
                'description_title_font_size' => 26,
                'description_title_direction' => 'left',
                'button_title' => 'Buy Now',
                'button_link' => 'https://demo.martvill.techvill.net/#',
                'button_font_color' => '#2c2c2c',
                'button_bg_color' => '#ffffff',
                'button_position' => 'left',
                'button_animation' => 'fadeIn',
                'button_delay' => NULL,
                'is_open_in_new_window' => 'Yes',
            ),
        );

        $replaceFrom = [
            'https:\\/\\/demo.martvill.techvill.net\\',
            'https://demo.martvill.techvill.net'
        ];

        $replaceTo = url('/');

        array_walk_recursive($data, function (&$value) use ($replaceFrom, $replaceTo) {
            $value = str_replace($replaceFrom, $replaceTo, $value);
        });

        \DB::table('slides')->delete();

        \DB::table('slides')->insert($data);

    }
}
