<?php

namespace Modules\Coupon\Database\Seeders;

use Illuminate\Database\Seeder;

class CouponsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('coupons')->delete();

        \DB::table('coupons')->insert(array(
            0 =>
            array(
                'id' => 2,
                'name' => 'Coupon1',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 5,
                'minimum_spend' => '3000.00000000',
                'usage_count' => NULL,
                'code' => 'xyz012',
                'discount_type' => 'Percentage',
                'discount_amount' => '30.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            1 =>
            array(
                'id' => 3,
                'name' => 'Eid Special',
                'vendor_id' => NULL,
                'shop_id' => NULL,
                'usage_limit' => 5,
                'minimum_spend' => NULL,
                'usage_count' => NULL,
                'code' => 'EID012',
                'discount_type' => 'Flat',
                'discount_amount' => '500.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            2 =>
            array(
                'id' => 4,
                'name' => 'Eid coupon',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 7,
                'minimum_spend' => '3000.00000000',
                'usage_count' => NULL,
                'code' => 'ramadan55',
                'discount_type' => 'Percentage',
                'discount_amount' => '30.00000000',
                'maximum_discount_amount' => '1500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            3 =>
            array(
                'id' => 5,
                'name' => 'coupon2',
                'vendor_id' => NULL,
                'shop_id' => NULL,
                'usage_limit' => 2,
                'minimum_spend' => '5000.00000000',
                'usage_count' => NULL,
                'code' => 'xyz-12',
                'discount_type' => 'Percentage',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => '3000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            4 =>
            array(
                'id' => 6,
                'name' => 'coupon3',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 1,
                'minimum_spend' => '3000.00000000',
                'usage_count' => NULL,
                'code' => 'code123',
                'discount_type' => 'Percentage',
                'discount_amount' => '99.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            5 =>
            array(
                'id' => 7,
                'name' => 'coupon6',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => NULL,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'code--012',
                'discount_type' => 'Flat',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            6 =>
            array(
                'id' => 8,
                'name' => 'coupon4',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 1,
                'minimum_spend' => '5000.00000000',
                'usage_count' => NULL,
                'code' => 'codexyz',
                'discount_type' => 'Percentage',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            7 =>
            array(
                'id' => 9,
                'name' => 'coupon5',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 4,
                'minimum_spend' => '5000.00000000',
                'usage_count' => NULL,
                'code' => 'code40',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            8 =>
            array(
                'id' => 10,
                'name' => 'coupon7',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 2,
                'minimum_spend' => '10000.00000000',
                'usage_count' => NULL,
                'code' => 'code50',
                'discount_type' => 'Percentage',
                'discount_amount' => '80.00000000',
                'maximum_discount_amount' => '5000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            9 =>
            array(
                'id' => 11,
                'name' => 'coupon8',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 3,
                'minimum_spend' => NULL,
                'usage_count' => NULL,
                'code' => 'promo2022',
                'discount_type' => 'Flat',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            10 =>
            array(
                'id' => 12,
                'name' => 'coupon9',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 10,
                'minimum_spend' => '10000.00000000',
                'usage_count' => NULL,
                'code' => 'coupon100',
                'discount_type' => 'Percentage',
                'discount_amount' => '60.00000000',
                'maximum_discount_amount' => '500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            11 =>
            array(
                'id' => 13,
                'name' => 'coupon10',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 10,
                'minimum_spend' => NULL,
                'usage_count' => NULL,
                'code' => 'Flat50',
                'discount_type' => 'Flat',
                'discount_amount' => '50.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            12 =>
            array(
                'id' => 14,
                'name' => 'coupon11',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => NULL,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'couponcode',
                'discount_type' => 'Percentage',
                'discount_amount' => '40.00000000',
                'maximum_discount_amount' => '500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            13 =>
            array(
                'id' => 15,
                'name' => 'coupon13',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 8,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'code0000',
                'discount_type' => 'Percentage',
                'discount_amount' => '20.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            14 =>
            array(
                'id' => 16,
                'name' => 'coupon15',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => NULL,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'coupon15',
                'discount_type' => 'Flat',
                'discount_amount' => '20.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            15 =>
            array(
                'id' => 17,
                'name' => 'coupon16',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => NULL,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'code60',
                'discount_type' => 'Percentage',
                'discount_amount' => '20.00000000',
                'maximum_discount_amount' => '500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            16 =>
            array(
                'id' => 18,
                'name' => 'Eid',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 1,
                'minimum_spend' => '200.00000000',
                'usage_count' => NULL,
                'code' => 'MOONeid',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            17 =>
            array(
                'id' => 19,
                'name' => 'Clark Dominguez',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 1,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'mkknkdMMr',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            18 =>
            array(
                'id' => 20,
                'name' => 'Clark Doominguez',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 1,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'MOOoNeid',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            19 =>
            array(
                'id' => 21,
                'name' => 'Picked Up',
                'vendor_id' => 1,
                'shop_id' => NULL,
                'usage_limit' => 1,
                'minimum_spend' => '1000.00000000',
                'usage_count' => NULL,
                'code' => 'mkknkdMMr9',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => NULL,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => NULL,
            ),
        ));
    }
}
